site_name: 硬件知识库
site_description: 硬件设计与嵌入式开发知识库
# site_url: https://your-domain.com/  # 改成你自己的域名
# repo_url: https://github.com/your-username/your-repo  # 改成你自己的仓库
INHERIT: mkdocs.nav.yml

theme:
  name: material
  font: false
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/eye
        name: 切换暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/eye-outline
        name: 切换亮色模式
  language: zh
  logo: img/logo-zip.png
  favicon: img/logo.svg
  features:
    - content.code.copy
    # - content.action.edit
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
  icon:
    repo: material/github

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      js_files:
        - javascripts/mathjax.js
      css_files:
        - stylesheets/extra.css

extra:
  generator: false
  # analytics:  # 取消注释并填入你的 GA 代码
  #   provider: google
  #   property: G-XXXXXXXXXX

copyright: Copyright &copy; since 2025

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/pangu/4.0.7/pangu.min.js
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
